### ISSUE TITLE
GitOps module for Maximo - Oil & Gas Industry Solution

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#20]
Docs: https://www.ibm.com/docs/en/mfo-and-g/7.6.2

- Cluster
- RWX Storage
- Maximo Manage
- `oilandgas` component
- Database connection (JDBC)
- Scheduler Optimization

```
spec:
  bindings:
    jdbc: workspace-application
    mso: workspace
  components:
    base:
      version: latest
    oilandgas:
      version: latest
  settings:
    deployment: {}
```

Does maximo workspace get created automatically?

<img width="912" alt="image" src="https://user-images.githubusercontent.com/102552179/165860559-f0470fc9-050e-4fe6-bbad-dbd736fa576e.png">
