### ISSUE TITLE
Web Terminal (Web Console) Automation

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#417]
Need automation to deploy the OpenShift web terminal (console).   The module needs to:

1. Deploy the DevWorkspace operator
2. Deploy the Web Terminal operator
3. After the operators are deployed, modify/patch the `web-terminal-tooling` `DevWorkspaceTemplate` instance in the `openshift-operators` namespace so that is uses our web-terminal images (can use cloud-specific images too).

ex: 
```
spec:
  components:
    - container:
        args:
          - tail
          - '-f'
          - /dev/null
        cpuLimit: 400m
        cpuRequest: 100m
        image: 'quay.io/cloudnativetoolkit/web-terminal:latest'
        memoryLimit: 256Mi
        memoryRequest: 128Mi
        mountSources: false
        sourceMapping: /projects
      name: web-terminal-tooling
```
